apiVersion: v1
kind: Service
metadata:
  name: vdi-postgres
  namespace: default
spec:
  type: NodePort       # 여기!
  selector:
    app: vdi-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30032  # 30000 ~ 32767 아무거나 지정 (예: 30032)
      protocol: TCP
      name: postgres
