apiVersion: v1
kind: Service
metadata:
  name: gui-pod-service
  namespace: default
spec:
  type: NodePort
  selector:
    user: user1   # (유저별로 라벨 동기화!)
  ports:
    - port: 6080
      targetPort: 6080
      protocol: TCP
      nodePort: 30680
